server:
  port: 9090
  servlet:
    context-path: /test
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?serverTimezone=GMT
    username: root
    password: etoak
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.benjamin
