server:
  port: 8888
  servlet:
    context-path: /boot
spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///test?serverTimezone=GMT
    username: root
    password: etoak
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  #type-aliases-package: com.etoak.bean
pagehelper:
  reasonable: true


qiniu:
  domain: https://resource.uat.bizvane.cn/
